# Generated by Django 3.0.7 on 2020-06-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_roleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('300', '300'), ('200', '200'), ('400', '400'), ('100', '100'), ('500', '500')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=34),
        ),
    ]
