# Generated by Django 3.0.7 on 2020-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200630_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdb',
            old_name='StudentId',
            new_name='StudentUser',
        ),
        migrations.AddField(
            model_name='studentdb',
            name='StudentID',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('CS', 'computer science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('100', '100'), ('500', '500'), ('300', '300'), ('200', '200')], default='student', max_length=34),
        ),
    ]
