# Generated by Django 3.0.7 on 2020-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200630_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('MHE', 'mechnical engineering'), ('CS', 'computer science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('400', '400'), ('500', '500'), ('300', '300'), ('200', '200')], default='student', max_length=34),
        ),
    ]
