# Generated by Django 3.0.7 on 2020-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200630_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('CS', 'computer science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('300', '300'), ('500', '500'), ('200', '200'), ('400', '400'), ('100', '100')], default='student', max_length=34),
        ),
    ]
