# Generated by Django 3.0.7 on 2020-07-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200630_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('500', '500'), ('300', '300'), ('400', '400'), ('200', '200')], default='student', max_length=34),
        ),
    ]
