# Generated by Django 3.0.7 on 2020-07-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200704_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherId', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('MHE', 'mechnical engineering'), ('CS', 'computer science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('500', '500'), ('200', '200'), ('300', '300'), ('400', '400')], default='student', max_length=34),
        ),
    ]
