# Generated by Django 3.0.7 on 2020-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200711_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('200', '200'), ('400', '400'), ('300', '300'), ('500', '500'), ('100', '100')], default='student', max_length=34),
        ),
    ]
