# Generated by Django 3.0.7 on 2020-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200711_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('CS', 'computer science'), ('PS', 'political science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('300', '300'), ('200', '200'), ('100', '100'), ('400', '400'), ('500', '500')], default='student', max_length=34),
        ),
    ]
