# Generated by Django 3.0.7 on 2020-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200711_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('MHE', 'mechnical engineering'), ('CS', 'computer science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('500', '500'), ('400', '400'), ('200', '200'), ('100', '100'), ('300', '300')], default='student', max_length=34),
        ),
    ]
