# Generated by Django 3.0.7 on 2020-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200711_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('CS', 'computer science'), ('PS', 'political science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('200', '200'), ('300', '300'), ('500', '500'), ('100', '100')], default='student', max_length=34),
        ),
    ]
