# Generated by Django 3.0.7 on 2020-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200711_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('MHE', 'mechnical engineering'), ('CS', 'computer science'), ('PS', 'political science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('200', '200'), ('100', '100'), ('300', '300'), ('500', '500')], default='student', max_length=34),
        ),
    ]
