# Generated by Django 3.0.7 on 2020-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200711_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_eat_pizzas', 'Can eat pizzas')]},
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('100', '100'), ('300', '300'), ('200', '200'), ('500', '500')], default='student', max_length=34),
        ),
    ]
