# Generated by Django 2.1.15 on 2020-07-24 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_auto_20200718_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdb',
            name='TeacherFname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherdb',
            name='TeacherSname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherdb',
            name='TeacherUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('PS', 'political science'), ('CS', 'computer science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('300', '300'), ('100', '100'), ('400', '400'), ('500', '500'), ('200', '200')], default='student', max_length=34),
        ),
    ]
