# Generated by Django 2.1.15 on 2020-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200724_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=34),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('300', '300'), ('200', '200'), ('500', '500'), ('400', '400')], default='student', max_length=34),
        ),
    ]
