# Generated by Django 2.1.15 on 2020-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200728_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roleUser',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='StudentCourse',
            field=models.CharField(choices=[('CS', 'computer science'), ('MHE', 'mechnical engineering'), ('PS', 'political science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('500', '500'), ('300', '300'), ('400', '400'), ('200', '200')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='semester',
            field=models.CharField(choices=[('2', '2'), ('1', '1')], default='1', max_length=34),
        ),
    ]
