# Generated by Django 2.1.15 on 2020-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20200809_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('300', '300'), ('100', '100'), ('500', '500'), ('200', '200')], default='student', max_length=34),
        ),
    ]
