# Generated by Django 3.0.7 on 2020-07-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200711_2104'),
        ('courseDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='Courses',
            field=models.CharField(choices=[('MHE', 'mechnical engineering'), ('CS', 'computer science'), ('PS', 'political science')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('400', '400'), ('200', '200'), ('100', '100'), ('300', '300'), ('500', '500')], default='student', max_length=34),
        ),
        migrations.CreateModel(
            name='CourseTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseDetail.CourseInfo')),
                ('Teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.TeacherDB')),
            ],
        ),
    ]
