# Generated by Django 2.1.15 on 2020-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0003_auto_20200718_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='Courses',
            field=models.CharField(choices=[('PS', 'political science'), ('CS', 'computer science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('300', '300'), ('100', '100'), ('400', '400'), ('500', '500'), ('200', '200')], default='student', max_length=34),
        ),
    ]
