# Generated by Django 2.1.15 on 2020-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0008_auto_20200728_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='Courses',
            field=models.CharField(choices=[('PS', 'political science'), ('CS', 'computer science'), ('MHE', 'mechnical engineering')], default='computer science', max_length=34),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('500', '500'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default='student', max_length=34),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=34),
        ),
    ]
