# Generated by Django 2.1.15 on 2020-08-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseDetail', '0010_auto_20200809_1820'),
        ('account', '0026_auto_20200809_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTakeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.IntegerField(default=1, max_length=20)),
                ('Semester', models.CharField(choices=[('2', '2'), ('1', '1')], default='1', max_length=34)),
                ('Date', models.DateTimeField()),
                ('CourseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseDetail.CourseInfo')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDB')),
            ],
        ),
        migrations.CreateModel(
            name='TakeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.IntegerField(default=1, max_length=20)),
                ('Semester', models.CharField(choices=[('2', '2'), ('1', '1')], default='1', max_length=34)),
                ('Date', models.DateTimeField()),
                ('CourseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseDetail.CourseInfo')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDB')),
            ],
        ),
    ]
